### ISSUE TITLE
panic error

### ISSUE THREAD

**Issue by rankeey** [lsds/KungFu#266]
@luomai @marwage , when run early bert demo, when update from one peers to 8 peers, panic happens, configuration is the same as the run.sh, error as follows:
updating to 1 peers: 169.254.128.33:13006
[I] updated to 1 peers: 169.254.128.33:13006
OK
[I] arrived at v11, new np=1, local: +0/-6, global: -0/14
[169.254.128.33.13000::[1;35mstderr[m] INFO:tensorflow:Saving checkpoints for 1047 into /cache/output/169.254.128.33-13000/model.ckpt.
[169.254.128.33.13003::[1;35mstderr[m] INFO:tensorflow:Saving checkpoints for 1047 into /cache/output/169.254.128.33-13003/model.ckpt.
[169.254.128.33.13001::[1;35mstderr[m] INFO:tensorflow:Saving checkpoints for 1047 into /cache/output/169.254.128.33-13001/model.ckpt.
[169.254.128.33.13002::[1;35mstderr[m] INFO:tensorflow:Saving checkpoints for 1047 into /cache/output/169.254.128.33-13002/model.ckpt.
[169.254.128.33.13006::stdout] sync offset 153320 -> 153320 on step 605
[169.254.128.33.13004::[1;35mstderr[m] INFO:tensorflow:Saving checkpoints for 1047 into /cache/output/169.254.128.33-13004/model.ckpt.
[169.254.128.33.13007::[1;35mstderr[m] INFO:tensorflow:Saving checkpoints for 1047 into /cache/output/169.254.128.33-13007/model.ckpt.
[169.254.128.33.13007::[1;35mstderr[m] WARNING:tensorflow:From /home/work/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py:966: remove_checkpoint (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
[169.254.128.33.13007::[1;35mstderr[m] Instructions for updating:
[169.254.128.33.13007::[1;35mstderr[m] Use standard file APIs to delete files with this prefix.
[169.254.128.33.13003::stdout] stopped after trained 153320 samples in 138 steps due to change cluster
[169.254.128.33.13001::stdout] stopped after trained 153320 samples in 138 steps due to change cluster
[169.254.128.33.13004::stdout] stopped after trained 153320 samples in 138 steps due to change cluster
[169.254.128.33.13002::stdout] stopped after trained 153320 samples in 138 steps due to change cluster
[169.254.128.33.13000::stdout] stopped after trained 153320 samples in 138 steps due to change cluster
[169.254.128.33.13007::stdout] stopped after trained 153320 samples in 138 steps due to change cluster
[169.254.128.33.13003::[1;35mstderr[m] INFO:tensorflow:Loss for final step: 1.1395919.
[169.254.128.33.13003::[1;35mstderr[m] INFO:tensorflow:training_loop marked as finished
[169.254.128.33.13003::[1;35mstderr[m] INFO:tensorflow:Training end time 2020-03-13 12:45:42.733748
[169.254.128.33.13001::[1;35mstderr[m] INFO:tensorflow:Loss for final step: 1.4893956.
[169.254.128.33.13001::[1;35mstderr[m] INFO:tensorflow:training_loop marked as finished
[169.254.128.33.13001::[1;35mstderr[m] INFO:tensorflow:Training end time 2020-03-13 12:45:42.850651
[169.254.128.33.13004::[1;35mstderr[m] INFO:tensorflow:Loss for final step: 1.357612.
[169.254.128.33.13004::[1;35mstderr[m] INFO:tensorflow:training_loop marked as finished
[169.254.128.33.13004::[1;35mstderr[m] INFO:tensorflow:Training end time 2020-03-13 12:45:42.928306
[169.254.128.33.13002::[1;35mstderr[m] INFO:tensorflow:Loss for final step: 1.4187098.
[169.254.128.33.13002::[1;35mstderr[m] INFO:tensorflow:training_loop marked as finished
[169.254.128.33.13002::[1;35mstderr[m] INFO:tensorflow:Training end time 2020-03-13 12:45:43.183136
[169.254.128.33.13000::[1;35mstderr[m] INFO:tensorflow:Loss for final step: 1.1474836.
[169.254.128.33.13000::[1;35mstderr[m] INFO:tensorflow:training_loop marked as finished
[169.254.128.33.13000::[1;35mstderr[m] INFO:tensorflow:Training end time 2020-03-13 12:45:43.285399
[169.254.128.33.13007::[1;35mstderr[m] INFO:tensorflow:Loss for final step: 2.2803762.
[169.254.128.33.13007::[1;35mstderr[m] INFO:tensorflow:training_loop marked as finished
[169.254.128.33.13007::[1;35mstderr[m] INFO:tensorflow:Training end time 2020-03-13 12:45:43.593442
[169.254.128.33.13006::[1;35mstderr[m] INFO:tensorflow:global_step/sec: 0.469528
[169.254.128.33.13006::[1;35mstderr[m] INFO:tensorflow:examples/sec: 3.75623
[169.254.128.33.13006::[1;35mstderr[m] INFO:tensorflow:global_step/sec: 3.41049
[169.254.128.33.13006::[1;35mstderr[m] INFO:tensorflow:examples/sec: 27.2839
[169.254.128.33.13006::[1;35mstderr[m] INFO:tensorflow:global_step/sec: 3.41522
[169.254.128.33.13006::[1;35mstderr[m] INFO:tensorflow:examples/sec: 27.3218
[169.254.128.33.13006::[1;35mstderr[m] INFO:tensorflow:Saving checkpoints for 1390 into /cache/output/169.254.128.33-13006/model.ckpt.
[169.254.128.33.13006::[1;35mstderr[m] INFO:tensorflow:global_step/sec: 3.1294
[169.254.128.33.13006::[1;35mstderr[m] INFO:tensorflow:examples/sec: 25.0352
[169.254.128.33.13006::[1;35mstderr[m] INFO:tensorflow:global_step/sec: 3.41119
[169.254.128.33.13006::[1;35mstderr[m] INFO:tensorflow:examples/sec: 27.2895
updating to 8 peers: 169.254.128.33:13002,169.254.128.114:13006,169.254.128.114:13005,169.254.128.33:13001,169.254.128.114:13002,169.254.128.114:13001,169.254.128.114:13000,169.254.128.33:13005
[I] updated to 8 peers: 169.254.128.33:13002,169.254.128.114:13006,169.254.128.114:13005,169.254.128.33:13001,169.254.128.114:13002,169.254.128.114:13001,169.254.128.114:13000,169.254.128.33:13005
OK
[1;35m[E][m full update detected: [1@2]{169.254.128.33:13006}@{169.254.128.33:38080,169.254.128.114:38080} -> [8@2]{169.254.128.33:13002,169.254.128.114:13006,169.254.128.114:13005,169.254.128.33:13001,169.254.128.114:13002,169.254.128.114:13001,169.254.128.114:13000,169.254.128.33:13005}@{169.254.128.33:38080,169.254.128.114:38080}
[I] arrived at v12, new np=8, local: +3/-1, global: -8/1
[169.254.128.33.13006::[1;35mstderr[m] panic: runtime error: invalid memory address or nil pointer dereference
[169.254.128.33.13006::[1;35mstderr[m] [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x7fab3df583c5]
[169.254.128.33.13006::[1;35mstderr[m] 
[169.254.128.33.13006::[1;35mstderr[m] goroutine 2706338 [running]:
[169.254.128.33.13006::[1;35mstderr[m] encoding/binary.Write(0x0, 0x0, 0x7fab3e4a5300, 0x7fab3e6c5900, 0x7fab3e4166e0, 0xc0007fa548, 0x6, 0xc0007fa540)
[169.254.128.33.13006::[1;35mstderr[m] 	/usr/local/go/src/encoding/binary/binary.go:342 +0x145
[169.254.128.33.13006::[1;35mstderr[m] github.com/lsds/KungFu/srcs/go/rchannel.(*messageHeader).WriteTo(0xc0b92adda8, 0x0, 0x0, 0x0, 0x0)
[169.254.128.33.13006::[1;35mstderr[m] 	/tmp/pip-req-build-3r6z01fr/srcs/go/rchannel/message.go:84 +0x78
[169.254.128.33.13006::[1;35mstderr[m] github.com/lsds/KungFu/srcs/go/rchannel.(*tcpConnection).Send(0xc0006bccf0, 0x7fab3e10338a, 0x6, 0x17d, 0xc000320000, 0x17d, 0x17d, 0x0, 0x7fab00000000, 0x0, ...)
[169.254.128.33.13006::[1;35mstderr[m] 	/tmp/pip-req-build-3r6z01fr/srcs/go/rchannel/connection.go:106 +0x16b
[169.254.128.33.13006::[1;35mstderr[m] github.com/lsds/KungFu/srcs/go/rchannel.(*Router).send(0xc000174db0, 0x94c0a9fe8072, 0x7fab3e10338a, 0x6, 0x17d, 0xc000320000, 0x17d, 0x17d, 0x0, 0x1, ...)
[169.254.128.33.13006::[1;35mstderr[m] 	/tmp/pip-req-build-3r6z01fr/srcs/go/rchannel/router.go:53 +0xc0
[169.254.128.33.13006::[1;35mstderr[m] github.com/lsds/KungFu/srcs/go/rchannel.(*Router).Send(0xc000174db0, 0x94c0a9fe8072, 0x7fab3e10338a, 0x6, 0xc000320000, 0x17d, 0x17d, 0x320001, 0x17d, 0x17d)
[169.254.128.33.13006::[1;35mstderr[m] 	/tmp/pip-req-build-3r6z01fr/srcs/go/rchannel/router.go:44 +0xeb
[169.254.128.33.13006::[1;35mstderr[m] github.com/lsds/KungFu/srcs/go/kungfu.(*Kungfu).propose.func1(0x94c0a9fe8072, 0x5a, 0x5a)
[169.254.128.33.13006::[1;35mstderr[m] 	/tmp/pip-req-build-3r6z01fr/srcs/go/kungfu/kungfu.go:204 +0xfc
[169.254.128.33.13006::[1;35mstderr[m] github.com/lsds/KungFu/srcs/go/kungfu.par.func1(0xc00022c0f0, 0xc0002500c0, 0x2, 0x2, 0xc00031e230, 0x1, 0x94c0a9fe8072)
[169.254.128.33.13006::[1;35mstderr[m] 	/tmp/pip-req-build-3r6z01fr/srcs/go/kungfu/kungfu.go:171 +0x3e
[169.254.128.33.13006::[1;35mstderr[m] created by github.com/lsds/KungFu/srcs/go/kungfu.par
[169.254.128.33.13006::[1;35mstderr[m] 	/tmp/pip-req-build-3r6z01fr/srcs/go/kungfu/kungfu.go:170 +0x10f
[I] 169.254.128.33.13006 finished with error: signal: aborted (core dumped)
exit on error: signal: aborted (core dumped)

**Comment by luomai** [comment]
@lgarithm

**Comment by marwage** [comment]
@rankeey you are not using the default port range. Did you specify the `-port-range` flag?

**Comment by lgarithm** [comment]
I think this is due to error not checked in 

https://github.com/lsds/KungFu/blob/ef468345570a31968ec03454b0424085483cfd5c/srcs/go/rchannel/connection.go#L84
